1Cezzo/idatt2105-project-backend

pom.xml
src/main/java/com/IDATT2105/IDATT2105Backend/Idatt2105BackendApplication.java

Changed naming convention so it doesn't include capital letters

fixed naming convention

---

src/main/java/com/IDATT2105/IDATT2105Backend/Idatt2105BackendApplication.java

Fixed some capital letters and such for class name

fixes class name

---

pom.xml
src/main/java/com/idatt2105/backend/controller/UserController.java
src/main/java/com/idatt2105/backend/model/User.java
src/main/java/com/idatt2105/backend/repositories/UserRepository.java
src/main/java/com/idatt2105/backend/security/UserService.java
src/main/java/com/idatt2105/backend/service/UserService.java
src/main/resources/application.properties

Created basic model, repository, service for user
Added dependency for mysql connection, updated application.properties

Implement users

---

pom.xml
src/main/java/com/idatt2105/backend/controller/QuizController.java
src/main/java/com/idatt2105/backend/model/Quiz.java
src/main/java/com/idatt2105/backend/model/User.java
src/main/java/com/idatt2105/backend/repositories/QuizRepository.java
src/main/java/com/idatt2105/backend/service/QuizService.java
src/main/java/com/idatt2105/backend/service/UserService.java

created Quiz model, repository and service, created many to many relation with user

Quiz model, repository and service, many to many with user

---

LICENSE
src/main/java/com/idatt2105/backend/controller/CommentController.java
src/main/java/com/idatt2105/backend/controller/QuizController.java
src/main/java/com/idatt2105/backend/model/Comment.java
src/main/java/com/idatt2105/backend/repositories/CommentRepository.java
src/main/java/com/idatt2105/backend/service/CommentService.java
src/main/java/com/idatt2105/backend/service/QuizService.java

Added comment model, repository, service and controller
Added functionality in service classes and quiz controller

Added comment model, repository, service and controller.

---

.gitignore
pom.xml
src/main/java/com/idatt2105/backend/controller/FeedbackController.java
src/main/java/com/idatt2105/backend/dto/CommentDTO.java
src/main/java/com/idatt2105/backend/dto/FeedbackDTO.java
src/main/java/com/idatt2105/backend/enumerator/FeedbackType.java
src/main/java/com/idatt2105/backend/model/Feedback.java
src/main/java/com/idatt2105/backend/repository/FeedbackRepository.java
src/main/java/com/idatt2105/backend/service/FeedbackService.java

Implemented feedback model, DTO, repository, service and controller
Added enum class for feedback type

Implement feedback

---

src/main/java/com/idatt2105/backend/controller/AttemptController.java
src/main/java/com/idatt2105/backend/controller/QuestionController.java
src/main/java/com/idatt2105/backend/dto/AlternativeDTO.java
src/main/java/com/idatt2105/backend/dto/QuestionAttemptDTO.java
src/main/java/com/idatt2105/backend/dto/QuestionDTO.java
src/main/java/com/idatt2105/backend/dto/QuizAttemptDTO.java
src/main/java/com/idatt2105/backend/model/AlternativeRecord.java
src/main/java/com/idatt2105/backend/model/MultipleChoiceQuestion.java
src/main/java/com/idatt2105/backend/model/MultipleChoiceQuestionAttempt.java
src/main/java/com/idatt2105/backend/model/Question.java
src/main/java/com/idatt2105/backend/model/QuestionAttempt.java
src/main/java/com/idatt2105/backend/model/QuestionType.java
src/main/java/com/idatt2105/backend/model/Quiz.java
src/main/java/com/idatt2105/backend/model/QuizAttempt.java
src/main/java/com/idatt2105/backend/model/TrueOrFalseQuestion.java
src/main/java/com/idatt2105/backend/model/TrueOrFalseQuestionAttempt.java
src/main/java/com/idatt2105/backend/model/User.java
src/main/java/com/idatt2105/backend/repository/QuizAttemptRepository.java
src/main/java/com/idatt2105/backend/service/AttemptService.java
src/main/java/com/idatt2105/backend/service/QuestionService.java
src/main/java/com/idatt2105/backend/util/NoNullElements.java
src/main/java/com/idatt2105/backend/util/NoNullElementsValidator.java

Added functionality for storing quiz attempts, currently with multiple choice and true/false questions

Implement attempt

---

pom.xml
src/main/java/com/idatt2105/backend/Idatt2105BackendApplication.java
src/main/java/com/idatt2105/backend/model/User.java
src/main/java/com/idatt2105/backend/security/SecurityConfig.java
src/main/java/com/idatt2105/backend/service/UserService.java
src/test/java/com/idatt2105/backend/user/UserServiceTest.java

updated tests to accommodate for this change
created security config, gave access to all endpoints > remove this before production

added hashing and salting to user password

---

src/main/java/com/idatt2105/backend/controller/ImageController.java
src/main/java/com/idatt2105/backend/dto/UserDTO.java
src/main/java/com/idatt2105/backend/service/UserService.java

fixed some errors I discovered while connecting backend and frontend together

fixed some errors

---

src/main/java/com/idatt2105/backend/controller/ImageController.java

fixed small error in endpoint for image uploading/deleting

fixed small error in endpoint for image uploading/deleting

---

src/main/java/com/idatt2105/backend/controller/EmailController.java
src/main/java/com/idatt2105/backend/controller/ImageController.java
src/main/java/com/idatt2105/backend/controller/PasswordResetTokenController.java
src/main/java/com/idatt2105/backend/dto/PasswordResetTokenDTO.java
src/main/java/com/idatt2105/backend/model/PasswordResetToken.java
src/main/java/com/idatt2105/backend/repository/PasswordResetTokenRepository.java
src/main/java/com/idatt2105/backend/service/PasswordResetTokenService.java
src/main/java/com/idatt2105/backend/service/UserService.java

fixed endpoint for deleting image so it works in frontend

hotfix for delete file endpoint, added PasswordResetToken

---

src/main/java/com/idatt2105/backend/dto/QuizDTO.java
src/main/java/com/idatt2105/backend/model/Quiz.java
src/main/java/com/idatt2105/backend/service/QuizService.java

added isPublic and isRandomizedOrder to quiz
if you leave them empty when creating the quiz, they are both set to false
you can change their values by using the update quiz endpoint

added isPublic and isRandomizedOrder to quiz

---

src/main/java/com/idatt2105/backend/controller/QuizController.java
src/main/java/com/idatt2105/backend/dto/QuizDTO.java
src/main/java/com/idatt2105/backend/model/Quiz.java
src/main/java/com/idatt2105/backend/service/QuizService.java
src/test/java/com/idatt2105/backend/service/QuizServiceTests.java

added update tags endpoint which I can use in my update quiz page

added update tags endpoint to be able to use in frontend

---

src/main/java/com/idatt2105/backend/controller/EmailController.java
src/main/java/com/idatt2105/backend/controller/QuizController.java
src/main/java/com/idatt2105/backend/security/ResourceServerConfig.java

Some endpoints are required for all users, without logging in (such as getting quizzes, searching by category etc.). These endpoints have been opened so that they do not require authentication to use.

Endpoint permissions

---

src/main/java/com/idatt2105/backend/controller/QuestionController.java
src/main/java/com/idatt2105/backend/model/Alternative.java
src/main/java/com/idatt2105/backend/service/QuestionService.java

added a method and endpoint to update the alternatives for a question

Hotfix update alternatives

---

src/main/java/com/idatt2105/backend/controller/QuizController.java
src/main/java/com/idatt2105/backend/service/QuizService.java

added endpoint to be able to filter quizzes by a list of tags

added endpoint to filter by tags

---

src/main/java/com/idatt2105/backend/controller/QuizController.java
src/main/java/com/idatt2105/backend/service/QuizService.java

fixed filtering so the quiz needs to have at least the specified tags but can have more

fixed filtering

---

src/main/java/com/idatt2105/backend/controller/CommentController.java
src/main/java/com/idatt2105/backend/dto/UserDTO.java
src/main/java/com/idatt2105/backend/repository/CommentRepository.java
src/main/java/com/idatt2105/backend/service/CommentService.java
src/main/java/com/idatt2105/backend/service/UserService.java

added profile picture url in return from the getUserById method/endpoint
added pagination to comment retrieval

added pagination to comment retrieval

---

pom.xml
src/test/java/com/idatt2105/backend/dto/AlternativeDTOTests.java
src/test/java/com/idatt2105/backend/dto/CommentDTOTests.java
src/test/java/com/idatt2105/backend/dto/LoginRequestDTOTests.java
src/test/java/com/idatt2105/backend/dto/PasswordResetTokenDTOTest.java
src/test/java/com/idatt2105/backend/dto/QuestionAttemptDTOTests.java
src/test/java/com/idatt2105/backend/dto/QuestionDTOTests.java
src/test/java/com/idatt2105/backend/dto/QuizAttemptDTOTests.java
src/test/java/com/idatt2105/backend/dto/QuizUpdateRequestDTOTests.java
src/test/java/com/idatt2105/backend/dto/ResetRequestDTOTest.java
src/test/java/com/idatt2105/backend/model/CategoryTest.java
src/test/java/com/idatt2105/backend/model/CommentTests.java
src/test/java/com/idatt2105/backend/model/FeedbackTests.java
src/test/java/com/idatt2105/backend/model/MultipleChoiceQuestionTests.java
src/test/java/com/idatt2105/backend/model/PasswordResetTokenTest.java
src/test/java/com/idatt2105/backend/model/QuizAttemptTests.java
src/test/java/com/idatt2105/backend/service/PasswordResetTokenServiceTest.java
src/test/java/com/idatt2105/backend/service/QuestionServiceTests.java
src/test/java/com/idatt2105/backend/util/ErrorResponseTest.java
src/test/java/com/idatt2105/backend/util/ExistingUserExceptionTest.java
src/test/java/com/idatt2105/backend/util/InvalidCredentialsExceptionTest.java
src/test/java/com/idatt2105/backend/util/InvalidIdExceptionTest.java
src/test/java/com/idatt2105/backend/util/InvalidQuestionTypeExceptionTest.java
src/test/java/com/idatt2105/backend/util/RestExceptionHandlerTest.java
src/test/java/com/idatt2105/backend/util/UserNotFoundExceptionTest.java

improved test coverage, excluded AmazonClient from test coverage

improved test coverage, excluded AmazonClient from test coverage

---

src/main/java/com/idatt2105/backend/controller/PasswordResetTokenController.java
src/main/java/com/idatt2105/backend/controller/QuizController.java
src/main/java/com/idatt2105/backend/service/QuizService.java
src/test/java/com/idatt2105/backend/controller/QuizControllerTests.java
src/test/java/com/idatt2105/backend/service/QuizServiceTests.java

Remove delete quiz

---

src/main/java/com/idatt2105/backend/controller/UserController.java
src/main/java/com/idatt2105/backend/security/ResourceServerConfig.java
src/main/java/com/idatt2105/backend/security/SecurityConfig.java
src/main/java/com/idatt2105/backend/service/UserService.java
src/main/java/com/idatt2105/backend/util/DataLoader.java
src/main/resources/application.properties
src/test/java/com/idatt2105/backend/controller/UserControllerTest.java

Made some more detailed example quizzes, and removed some unused/broken endpoints

Add test data

---

pom.xml
src/test/java/com/idatt2105/backend/Idatt2105BackendApplicationTests.java
src/test/java/com/idatt2105/backend/controller/PasswordResetTokenControllerTest.java
src/test/java/com/idatt2105/backend/controller/QuizControllerTests.java
src/test/java/com/idatt2105/backend/service/QuestionServiceTests.java
src/test/java/com/idatt2105/backend/service/QuizServiceTests.java

added tests to increase test coverage, excluded tests that rely on external services as these are hard to test

increase test coverage

---

src/main/resources/static/stylesheet.css

changed background color and card color for login card so it matches frontend color

changed background color and card color so it matches frontend color
